apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: dl-phac-alpha-canada-ca-ns
  namespace: alpha-dns
  annotations:
    projectName: "Epicenter"
    gitHubRepository: "phac-epi-garden"
spec:
  name: "dl.phac.alpha.canada.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: phac-alpha-canada-ca
  rrdatas:
    - "ns-cloud-a1.googledomains.com."
    - "ns-cloud-a2.googledomains.com."
    - "ns-cloud-a3.googledomains.com."
    - "ns-cloud-a4.googledomains.com."
