apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: hellodjango-phac-aspc-alpha-canada-ca-ns
  namespace: alpha-dns
  annotations:
    projectName: "Hello Django"
    sourceCodeRepository: "https://github.com/PHACDataHub/cloudrun-deployment-example"
    serviceUrls: "https://hello-world-from-cloud-build-trigger-vlfae7w5dq-nn.a.run.app"
    containerRegistries: "northamerica-northeast1-docker.pkg.dev/phx-01h1yptgmche7jcy01wzzpw2rf/hello-world-app"
spec:
  name: "hellodjango.phac-aspc.alpha.canada.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: phac-aspc-alpha-canada-ca
  rrdatas:
    - "ns-cloud-e1.googledomains.com."
    - "ns-cloud-e2.googledomains.com."
    - "ns-cloud-e3.googledomains.com."
    - "ns-cloud-e4.googledomains.com."
