apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: jitaccess-ops-phac-alpha-canada-ca-ns
  namespace: alpha-dns
  annotations:
    projectName: "JIT Access"
    sourceCodeRepository: "https://github.com/PHACDataHub/JIT-IaC"
spec:
  name: "jitaccess.ops.phac.alpha.canada.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: ops-phac-alpha-canada-ca-zone
  rrdatas:
    - "ns-cloud-a1.googledomains.com."
    - "ns-cloud-a2.googledomains.com."
    - "ns-cloud-a3.googledomains.com."
    - "ns-cloud-a4.googledomains.com."