apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: jitaccess-ops-phac-alpha-canada-ca-ns
  namespace: alpha-dns
  labels:
    ownerName: "Eric Malenfant"
    ownerContact: "eric.richard-malenfant@phac.aspc.gc.ca"
    gitHubRepo: "JIT-IaC"
spec:
  name: "jitaccess.ops.phac.alpha.canada.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: phac-alpha-canada-ca
  rrdatas:
    - "ns-cloud-a1.googledomains.com."
    - "ns-cloud-a2.googledomains.com."
    - "ns-cloud-a3.googledomains.com."
    - "ns-cloud-a4.googledomains.com."