apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: llm-phac-alpha-canada-ca-ns
  namespace: alpha-dns
spec:
  name: "llm.phac.alpha.canada.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: phac-alpha-canada-ca
  rrdatas:
    - "ns-cloud-c1.googledomains.com."
    - "ns-cloud-c2.googledomains.com."
    - "ns-cloud-c3.googledomains.com."
    - "ns-cloud-c4.googledomains.com."
