---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSManagedZone
metadata:
  name: ops-phac-alpha-canada-ca-zone
  namespace: alpha-dns 
spec:
  description: "Managed Zone for ops.phac.alpha.canada.ca"
  dnsName: "ops.phac.alpha.canada.ca."
  visibility: "public"
  dnssecConfig:
    state: "on"
    defaultKeySpecs:
      - algorithm: "rsasha256"
        keyLength: 2048
        keyType: "keySigning"
        kind: "dns#managedZoneDnsSecConfigDefaultKeySpecs"
      - algorithm: "rsasha256"
        keyLength: 1024
        keyType: "zoneSigning"
        kind: "dns#managedZoneDnsSecConfigDefaultKeySpecs"
---
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: ops-phac-alpha-canada-ca-ns
  namespace: alpha-dns
spec:
  name: "ops.phac.alpha.canada.ca."
  type: "NS"
  ttl: 300
  managedZoneRef:
    external: phac-alpha-canada-ca
  rrdatas:
    - "ns-cloud-c1.googledomains.com."
    - "ns-cloud-c2.googledomains.com."
    - "ns-cloud-c3.googledomains.com."
    - "ns-cloud-c4.googledomains.com."
